"""add storage location color

Revision ID: 0bd8ea844ff6
Revises: 49e4d98b9c38
Create Date: 2026-04-25 15:17:40.584730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0bd8ea844ff6'
down_revision: Union[str, Sequence[str], None] = '49e4d98b9c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('storage_location', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_location', 'color')
    # ### end Alembic commands ###
