"""add orders feature

Revision ID: 45d05a16c2d1
Revises: 0bd8ea844ff6
Create Date: 2026-04-26 03:58:30.280028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '45d05a16c2d1'
down_revision: Union[str, Sequence[str], None] = '0bd8ea844ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group_id')
    )
    op.create_index(op.f('ix_project_group_id'), 'project', ['group_id'], unique=False)
    op.create_index(op.f('ix_project_is_archived'), 'project', ['is_archived'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_table('chemical_order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('chemical_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('amount_per_package', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('package_count', sa.Integer(), nullable=False),
    sa.Column('price_per_package', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('purity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor_catalog_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor_product_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vendor_order_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_arrival', sa.Date(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('ORDERED', 'RECEIVED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('ordered_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('received_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['ordered_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_order_chemical_id'), 'chemical_order', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_chemical_order_group_id'), 'chemical_order', ['group_id'], unique=False)
    op.create_index(op.f('ix_chemical_order_project_id'), 'chemical_order', ['project_id'], unique=False)
    op.create_index(op.f('ix_chemical_order_status'), 'chemical_order', ['status'], unique=False)
    op.create_index(op.f('ix_chemical_order_supplier_id'), 'chemical_order', ['supplier_id'], unique=False)
    op.create_table('wishlist_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('chemical_id', sa.Uuid(), nullable=True),
    sa.Column('freeform_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('freeform_cas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CONVERTED', 'DISMISSED', name='wishliststatus'), nullable=False),
    sa.Column('converted_to_order_id', sa.Uuid(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['converted_to_order_id'], ['chemical_order.id'], ),
    sa.ForeignKeyConstraint(['dismissed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wishlist_item_chemical_id'), 'wishlist_item', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_wishlist_item_group_id'), 'wishlist_item', ['group_id'], unique=False)
    op.create_index(op.f('ix_wishlist_item_status'), 'wishlist_item', ['status'], unique=False)
    with op.batch_alter_table('container') as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_container_order_id'), ['order_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_container_order_id_chemical_order', 'chemical_order', ['order_id'], ['id']
        )
    # ### end Alembic commands ###

    # --- Data migration: pre-seed General project + 10 supplier names per existing group.
    # Idempotent: skips suppliers that already exist for that group (case-insensitive on name).
    bind = op.get_bind()
    PRESEED_SUPPLIERS = [
        "Sigma-Aldrich", "Merck", "Carl Roth", "abcr", "BLDPharm",
        "TCI", "Alfa Aesar", "Fisher Scientific", "Thermo Fisher", "VWR",
    ]
    groups = bind.execute(sa.text("SELECT id FROM \"group\"")).fetchall()
    for (group_id,) in groups:
        # General project
        existing = bind.execute(
            sa.text(
                "SELECT id FROM project WHERE group_id = :gid AND name = :name"
            ),
            {"gid": group_id, "name": "General"},
        ).first()
        if existing is None:
            bind.execute(
                sa.text(
                    "INSERT INTO project (id, group_id, name, is_archived) "
                    "VALUES (:id, :gid, :name, 0)"
                ),
                {"id": str(__import__('uuid').uuid4()), "gid": group_id, "name": "General"},
            )
        # Pre-seeded suppliers (skip if already present case-insensitively)
        for supplier_name in PRESEED_SUPPLIERS:
            already = bind.execute(
                sa.text(
                    "SELECT id FROM supplier "
                    "WHERE group_id = :gid AND LOWER(name) = LOWER(:name)"
                ),
                {"gid": group_id, "name": supplier_name},
            ).first()
            if already is None:
                bind.execute(
                    sa.text(
                        "INSERT INTO supplier (id, group_id, name) "
                        "VALUES (:id, :gid, :name)"
                    ),
                    {
                        "id": str(__import__('uuid').uuid4()),
                        "gid": group_id,
                        "name": supplier_name,
                    },
                )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container') as batch_op:
        batch_op.drop_constraint('fk_container_order_id_chemical_order', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_container_order_id'))
        batch_op.drop_column('order_id')
    op.drop_index(op.f('ix_wishlist_item_status'), table_name='wishlist_item')
    op.drop_index(op.f('ix_wishlist_item_group_id'), table_name='wishlist_item')
    op.drop_index(op.f('ix_wishlist_item_chemical_id'), table_name='wishlist_item')
    op.drop_table('wishlist_item')
    op.drop_index(op.f('ix_chemical_order_supplier_id'), table_name='chemical_order')
    op.drop_index(op.f('ix_chemical_order_status'), table_name='chemical_order')
    op.drop_index(op.f('ix_chemical_order_project_id'), table_name='chemical_order')
    op.drop_index(op.f('ix_chemical_order_group_id'), table_name='chemical_order')
    op.drop_index(op.f('ix_chemical_order_chemical_id'), table_name='chemical_order')
    op.drop_table('chemical_order')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_is_archived'), table_name='project')
    op.drop_index(op.f('ix_project_group_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
