"""add container ordered_by_name

Revision ID: ab54b01e27a9
Revises: b4e7c1a29301
Create Date: 2026-04-22 18:40:32.510041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab54b01e27a9'
down_revision: Union[str, Sequence[str], None] = 'b4e7c1a29301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container', sa.Column('ordered_by_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_container_ordered_by_name'), 'container', ['ordered_by_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_container_ordered_by_name'), table_name='container')
    op.drop_column('container', 'ordered_by_name')
    # ### end Alembic commands ###
