"""initial schema

Revision ID: bb0857b3e226
Revises: 
Create Date: 2026-04-10 11:55:13.788125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb0857b3e226'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ghs_code',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pictogram', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signal_word', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ghs_code_code'), 'ghs_code', ['code'], unique=True)
    op.create_table('group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=True)
    op.create_table('hazard_tag',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazard_tag_name'), 'hazard_tag', ['name'], unique=True)
    op.create_table('storage_location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_location_parent_id'), 'storage_location', ['parent_id'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('chemical',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('smiles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('structure', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('molar_mass', sa.Float(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('melting_point', sa.Float(), nullable=True),
    sa.Column('boiling_point', sa.Float(), nullable=True),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_cas'), 'chemical', ['cas'], unique=False)
    op.create_index(op.f('ix_chemical_group_id'), 'chemical', ['group_id'], unique=False)
    op.create_index(op.f('ix_chemical_name'), 'chemical', ['name'], unique=False)
    op.create_table('hazard_tag_incompatibility',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag_a_id', sa.Uuid(), nullable=False),
    sa.Column('tag_b_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['tag_a_id'], ['hazard_tag.id'], ),
    sa.ForeignKeyConstraint(['tag_b_id'], ['hazard_tag.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_a_id', 'tag_b_id')
    )
    op.create_table('storage_location_group',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['storage_location.id'], ),
    sa.PrimaryKeyConstraint('location_id', 'group_id'),
    sa.UniqueConstraint('location_id', 'group_id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_group_id'), 'supplier', ['group_id'], unique=False)
    op.create_table('user_group_link',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id'),
    sa.UniqueConstraint('user_id', 'group_id')
    )
    op.create_table('chemical_ghs',
    sa.Column('chemical_id', sa.Uuid(), nullable=False),
    sa.Column('ghs_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['ghs_id'], ['ghs_code.id'], ),
    sa.PrimaryKeyConstraint('chemical_id', 'ghs_id'),
    sa.UniqueConstraint('chemical_id', 'ghs_id')
    )
    op.create_table('chemical_hazard_tag',
    sa.Column('chemical_id', sa.Uuid(), nullable=False),
    sa.Column('hazard_tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['hazard_tag_id'], ['hazard_tag.id'], ),
    sa.PrimaryKeyConstraint('chemical_id', 'hazard_tag_id'),
    sa.UniqueConstraint('chemical_id', 'hazard_tag_id')
    )
    op.create_table('chemical_synonym',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chemical_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_synonym_chemical_id'), 'chemical_synonym', ['chemical_id'], unique=False)
    op.create_table('container',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chemical_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['storage_location.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_container_chemical_id'), 'container', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_container_identifier'), 'container', ['identifier'], unique=False)
    op.create_index(op.f('ix_container_is_archived'), 'container', ['is_archived'], unique=False)
    op.create_index(op.f('ix_container_location_id'), 'container', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_container_location_id'), table_name='container')
    op.drop_index(op.f('ix_container_is_archived'), table_name='container')
    op.drop_index(op.f('ix_container_identifier'), table_name='container')
    op.drop_index(op.f('ix_container_chemical_id'), table_name='container')
    op.drop_table('container')
    op.drop_index(op.f('ix_chemical_synonym_chemical_id'), table_name='chemical_synonym')
    op.drop_table('chemical_synonym')
    op.drop_table('chemical_hazard_tag')
    op.drop_table('chemical_ghs')
    op.drop_table('user_group_link')
    op.drop_index(op.f('ix_supplier_group_id'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_table('storage_location_group')
    op.drop_table('hazard_tag_incompatibility')
    op.drop_index(op.f('ix_chemical_name'), table_name='chemical')
    op.drop_index(op.f('ix_chemical_group_id'), table_name='chemical')
    op.drop_index(op.f('ix_chemical_cas'), table_name='chemical')
    op.drop_table('chemical')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_storage_location_parent_id'), table_name='storage_location')
    op.drop_table('storage_location')
    op.drop_index(op.f('ix_hazard_tag_name'), table_name='hazard_tag')
    op.drop_table('hazard_tag')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_ghs_code_code'), table_name='ghs_code')
    op.drop_table('ghs_code')
    # ### end Alembic commands ###
